### ISSUE TITLE
KeyError:api

### ISSUE THREAD

**Issue by Kunlun-Zhu** [edreisMD/plugnplai#64] opened 2023-05-22 02:59 UTC
**Code:**
from plugnplai import Plugins[ 5] :
plugins = Plugins.install and activate(urls)
---------------------------------------------------------------------------------------------------------
**Error**
Http Error: 404 Client Error: Not Found for url: https://api. speak, com/%5c.wel1-knowm/ai-plugin. jsor
KeyErrorTraceback (most recent cal1 last)AppData\Local\Temp/ipykerne1_7340/3447704211.py in <module>l from plugrplai import Plugins
---> 3 plugins = Plugins.install and activate(urls)
E: Program Files (x86)Anaconda lib site-packagesiplugnplai plugins.py in instal1-and activate(cls, urls, template)213@classmethod214def install_and_activate(cls, urls: List[str], template: str = template_gpt4):--> 215instance = cls(urrls. templatel216for plugin name in instance.installed plugins.keys:217instance.activatelplugin namel
E: Program Files (x86)Anaconda lib site-packages plugnplai plugins.py in _-init_-(self, urls, template)209self.tokens = None210--> 211self.instal1 plugins(urls
212213@classmethod
E: Program Files (x86)Anaconda lib site-packages plugnplai plugins.py in instal1 plugins(self, urls,226def instal1 plugins(self, urls: List[str]]:227228I>
for url in urls:
manifest, openapi spec = spec from url(ur1)
openapi_object = PluginObject(openapi spec manifest!self.installed plugins[openapi_object.name for_model] = openapi_object
229230
E: Program Files (x86)Anaconda liblsite-packagesiplugnplailutils.py in spec from url(ur1)102 def spec_from url(ur1):
103
manifest = get_plugin manifest(ur1)
--> 104
openapi url = get_openapi url(url, manifest
105
openapi_spec = get_openapi_spec(openapi ur1)
106return manifest, openapi_spec
E: Program Files (x86)Anaconda lib site-packages plugnplailutils.py in get openapi url(url, manifest)75 # load the OpenAPI specification for the plugin, given the OpenAPI url described in the manifest file
76 def get_openapi ur1(ur1, manifest):
77
openapi urrl = manifest[rapi"][ur1*if openapi_ur1.startswith("/:
18
# remove slash in the end of url if present
79
KeyError:api

**Comment by edreisMD** [comment] 2023-05-23 03:59
I tried to reproduce the error, but I couldn't. Could you try `plugins = Plugins.install_and_activate(['https://api.speak.com'])` to see if this url is working?

**Comment by edreisMD** [comment] 2023-06-12 21:09
Hope it worked for you. Closing once we couldn't reproduce the error

**Closed by edreisMD** 2023-06-12 21:09 UTC
Labels: bug
